### ISSUE TITLE
Regarding suggestions 

### ISSUE THREAD

**Issue by yuliaerk** [taliab11/taliab11.github.io#4]
Hi Talia,
I really like your website and I wish you luck with rotations! 
I'm not going to make any drastic changes to the website look, just wanted to suggest adding more info about your skills (like CV part) and probably a few photos of your imaging, I guess as a person who works on cell-to-cell interaction you have plenty of it! Good luck!

**Comment by taliab11** [comment]
Thanks for the advice!
I don't have those photos yet since I just started, but hope to add them in the future :)
